- Derivan de la clase `RuntimeException`
- No requieren el uso de un bloque `try/catch`